baseurl                  = "https://visitmy.cloud"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Visit My Cloud"
theme                    = "slc"                      # install theme locally (git clone or submodule)
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "favicon.ico"
    homepage             = "main"                           # What to call the home page link, link will not be rendered if empty
    # footerText           = "Call me Sam, a theme for Hugo."

[[params.mainMenu]]
    link = "https://ctf.visitmy.cloud"
    text = "CTF Notepad"

[[params.mainMenu]]
    link = "https://www.thisismy.cloud/teamspeak3/"
    text = "Teamspeak 3 (Voice)"
